baseURL = "https://chantsune.github.io"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true
enableGitInfo = true

title = "エンジニアもどきの技術メモ"

theme = "mainroad"
paginate = 20

googleAnalytics = "UA-157456952-1"

[Author]
    name = "ChanTsune"
    bio = "C++とPythonが大好きなエンジニアもどきの技術メモ"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    customJs = ["https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2164456517159304"]
    copyright = "ChanTsune"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true
    googleFontsLink = "no"

[Params.style.vars]
  highlightColor = "#dc3545"

[Params.logo]
  image = "img/avatar.png"

[Params.widgets]
  tags_counter = true

[Params.widgets.social]
  github = "ChanTsune"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

[menu]
  [[menu.main]]
    identifier = "article"
    name = "articles"
    url = "/articles/"
  [[menu.footer]]
    name = "プライバシーボリシー"
    url = "/privacypolicy/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
